-- DiagAuto Connect - Supabase/Postgres schema

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  telephone VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_client VARCHAR(20) UNIQUE NOT NULL,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  telephone VARCHAR(20),
  whatsapp VARCHAR(30),
  adresse TEXT,
  statut VARCHAR(20) DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'actif', 'suspendu')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vehicules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  marque VARCHAR(100) NOT NULL,
  modele VARCHAR(100) NOT NULL,
  annee INT,
  immatriculation VARCHAR(50) UNIQUE NOT NULL,
  couleur VARCHAR(50),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS rendezvous (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  vehicule_id BIGINT NOT NULL REFERENCES vehicules(id) ON DELETE CASCADE,
  date_rdv DATE NOT NULL,
  heure_rdv TIME NOT NULL,
  motif TEXT,
  statut VARCHAR(20) DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'confirme', 'annule', 'termine')),
  notes_admin TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS interventions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rendezvous_id BIGINT REFERENCES rendezvous(id) ON DELETE SET NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  vehicule_id BIGINT NOT NULL REFERENCES vehicules(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  technicien VARCHAR(100),
  date_debut DATE,
  date_fin DATE,
  statut VARCHAR(20) DEFAULT 'en_cours' CHECK (statut IN ('en_cours', 'termine', 'suspendu')),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS devis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_devis VARCHAR(20) UNIQUE NOT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  vehicule_id BIGINT NOT NULL REFERENCES vehicules(id) ON DELETE CASCADE,
  intervention_id BIGINT REFERENCES interventions(id) ON DELETE SET NULL,
  date_devis DATE NOT NULL,
  date_validite DATE,
  statut VARCHAR(20) DEFAULT 'brouillon' CHECK (statut IN ('brouillon', 'envoye', 'accepte', 'refuse')),
  montant_ht NUMERIC(10,2) DEFAULT 0,
  tva NUMERIC(5,2) DEFAULT 20,
  montant_ttc NUMERIC(10,2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS proformas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_proforma VARCHAR(20) UNIQUE NOT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  vehicule_id BIGINT NOT NULL REFERENCES vehicules(id) ON DELETE CASCADE,
  date_proforma DATE NOT NULL,
  date_validite DATE,
  statut VARCHAR(20) DEFAULT 'brouillon' CHECK (statut IN ('brouillon', 'envoye', 'accepte', 'refuse')),
  montant_ht NUMERIC(10,2) DEFAULT 0,
  tva NUMERIC(5,2) DEFAULT 20,
  montant_ttc NUMERIC(10,2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS factures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_facture VARCHAR(20) UNIQUE NOT NULL,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  vehicule_id BIGINT NOT NULL REFERENCES vehicules(id) ON DELETE CASCADE,
  intervention_id BIGINT REFERENCES interventions(id) ON DELETE SET NULL,
  devis_id BIGINT REFERENCES devis(id) ON DELETE SET NULL,
  date_facture DATE NOT NULL,
  date_echeance DATE,
  statut VARCHAR(30) DEFAULT 'non_payee' CHECK (statut IN ('non_payee', 'partiellement_payee', 'payee')),
  montant_ht NUMERIC(10,2) DEFAULT 0,
  tva NUMERIC(5,2) DEFAULT 20,
  montant_ttc NUMERIC(10,2) DEFAULT 0,
  montant_paye NUMERIC(10,2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lignes_document (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_type VARCHAR(20) NOT NULL CHECK (document_type IN ('devis', 'proforma', 'facture')),
  document_id BIGINT NOT NULL,
  description VARCHAR(255) NOT NULL,
  quantite NUMERIC(10,2) DEFAULT 1,
  prix_unitaire NUMERIC(10,2) DEFAULT 0,
  montant NUMERIC(10,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS urgences_depannage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  telephone VARCHAR(50) NOT NULL,
  localisation VARCHAR(255) NOT NULL,
  zone VARCHAR(30) DEFAULT 'route_nationale' CHECK (zone IN ('route_nationale', 'hors_antananarivo', 'antananarivo', 'autre')),
  message TEXT NOT NULL,
  reponse_admin TEXT,
  client_notification_non_lue BOOLEAN DEFAULT FALSE,
  client_notification_version INT NOT NULL DEFAULT 0,
  statut VARCHAR(20) DEFAULT 'nouveau' CHECK (statut IN ('nouveau', 'vu', 'en_cours', 'traite', 'annule')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications_whatsapp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  destinataire VARCHAR(30),
  message TEXT NOT NULL,
  statut VARCHAR(40) NOT NULL CHECK (statut IN ('envoye', 'echec', 'configuration_manquante', 'numero_manquant')),
  erreur TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS atelier_config (
  id INT PRIMARY KEY DEFAULT 1,
  nom VARCHAR(150) DEFAULT 'DiagAuto Mada Service',
  adresse TEXT,
  telephone VARCHAR(100),
  whatsapp VARCHAR(100),
  email VARCHAR(150),
  facebook VARCHAR(150),
  site_web VARCHAR(150),
  nif VARCHAR(100),
  stat VARCHAR(100),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS urgences_depannage_updated_at ON urgences_depannage;
CREATE TRIGGER urgences_depannage_updated_at
BEFORE UPDATE ON urgences_depannage
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS atelier_config_updated_at ON atelier_config;
CREATE TRIGGER atelier_config_updated_at
BEFORE UPDATE ON atelier_config
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO atelier_config (id, nom, adresse, telephone, whatsapp, email, facebook)
VALUES (1, 'DiagAuto Mada Service', '67ha Nord Ouest Antananarivo', '034 61 721 32 / 034 76 562 52', '037 79 111 66', 'diagautomadagascar@gmail.com', 'DiagAuto Mada')
ON CONFLICT (id) DO NOTHING;

INSERT INTO admins (nom, prenom, email, password, telephone)
VALUES ('Admin', 'DiagAuto', 'admin@diagauto.mg', '$2a$10$.OxwlcLbqEq1il6yH3PGb.n8xzGp2P.MSF76RNQUkc8xTLNEd2YRm', '+261 34 00 000 00')
ON CONFLICT (email) DO NOTHING;
